name: flutter_animated_login
description: "A Flutter package to create a beautiful animated login screen with phone/email otp, password, and social login options. It also includes a phone number with country code picker."
version: 0.0.10
homepage: https://github.com/rvndsngwn/flutter_animated_login
repository: https://github.com/rvndsngwn/flutter_animated_login
issue_tracker: https://github.com/rvndsngwn/flutter_animated_login/issues
documentation: https://github.com/rvndsngwn/flutter_animated_login/blob/master/README.md
screenshots:
  - description: "Login Screen with Phone/Email"
    path: image-1.png
  - description: "OTP Verification Screen"
    path: image-2.png

topics:
  - flutter-login
  - flutter-animated-login
  - flutter-login-screen
  - flutter-login-ui
  - animated-login

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_intl_phone_field: ^0.0.4
  material_loading_buttons: ^1.2.1
  pinput: ^4.0.0
  signals: ^5.1.0
  toastification: ^1.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter: null
